### PR TITLE
Attempt to include coveralls

### PR DESCRIPTION
**Pull request by GiacomoPope**

### CODE REVIEW

**Comment by GiacomoPope** [comment]
Trying to make it work with: https://github.com/coverallsapp/coverage-reporter

**Comment by GiacomoPope** [comment]
So I think this is working now: https://coveralls.io/jobs/147503738 but I suppose I need some way to communicate this

**Comment by GiacomoPope** [comment]
@tomato42 seeing as this was your suggestion, do you have a "favourite way" to communicate the output from the CLI?

**Review by tomato42 — CHANGES_REQUESTED** [review]
coverage runs should be part of the normal runs; we use coveralls to combine runs from different environments into one coherent sum total, so we don't want a new Actions job, we want to modify existing ones that test with different python versions

**Comment by tomato42** [comment]
one tricky part is that after you create steps to upload the individual job results to coveralls, like so:
https://github.com/tlsfuzzer/python-ecdsa/blob/35c33f2e11e6f95b16cec3fe0eaa5d0e34082b18/.github/workflows/ci.yml#L372-L385

you need to then tell coveralls that all jobs finished and the test run is ready:
https://github.com/tlsfuzzer/python-ecdsa/blob/35c33f2e11e6f95b16cec3fe0eaa5d0e34082b18/.github/workflows/ci.yml#L387-L401

**Comment by GiacomoPope** [comment]
I'm finishing for the day now, I might pick this back up later. Feel free to tweak if you want.

**Comment by tomato42** [comment]
Fixed it up.

**Review by tomato42 — APPROVED** [review]

**Comment by GiacomoPope** [comment]
Thanks for fixing this for me

**Pull request merged**
