### PR TITLE
A start on type annotations

### PR DESCRIPTION
**Pull request by jpgoldberg**
The bulk of this PR is just an initial start on type annotations. It is a small start, but I would like to get this in place before working on some issues that pursuing this revealed.

What's here

- `kat_file` tests now work with pytest. (There was a function naming issue that messed up test discovery)
- A boatload of basic type annotations (A couple new types are created for Element and Coefficient, but I didn't want to do more of that sort of thing just yet)
- VSCode spellright dictionary.

I will create an issue for something that I think needs a bigger tidy that was revealed by my effort to start on type annotations.

### CODE REVIEW

**Comment by GiacomoPope** [comment]
This seems to have some conflicts. I'm out for the day but will have time to look this evening if the PR is in a state to merge. 

No rush my end though

**Comment by tomato42** [comment]
also, please make sure you're using correct key for the email you're using for commits

**Comment by jpgoldberg** [comment]
Oops. Sorry about the conflicts. I will sort them out.

**Comment by jpgoldberg** [comment]
> also, please make sure you're using correct key for the email you're using for commits

Will do.

**Comment by GiacomoPope** [comment]
Hey, I just wanted to reach out and say a lot of what I planned to do (add ML-KEM, add tests) is now done. What's left to do is docstrings and other documentation and so if you wanted to work on the type annotations there shouldn't be much churn anymore. Sorry for all the quick changes over the past few days.

**Pull request closed without merging**
